apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: poi
  name: poi
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: poi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: registryhcf6115.azurecr.io/poi                  #.spec.template.spec.containers.image
        env:
        - name: SQL_PASSWORD    # move to k8s secret !!!!
          #value: "sX5bu0Bl0"
          valueFrom:
            secretKeyRef:
              name: sql-creds
              key: SQL_PASSWORD
        - name: SQL_SERVER
          value: sqlserverhcf6115.database.windows.net
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: SQL_USER
          value: "sqladminhCf6115"
        imagePullPolicy: Always
        name: apacz-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
#  labels:
#    app: poi
  name: poi
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: poi
#  sessionAffinity: None
#  type: ClusterIP
